#  Añadir stock al inventario
POST http://localhost:3000/inventario
Content-Type: application/json

{
    "referencia": "CF-001",
    "items": [
        { "cantidadReposicion": 10 },
        { "cantidadReposicion": 5 }
    ]
}

# Consultar stock de un producto por el id
GET http://localhost:3000/inventario/10

# Actualizar la cantidad de stock de un producto
PATCH http://localhost:3000/inventario/10/cantidad
Content-Type: application/json
{
    "nuevaCantidad": 100
}